#!/bin/sh
set -ex

mkdir -p /dev/by-name
for part in ${partitions//:/ }; do 
   ln -fs "/dev/${part#*@}" "/dev/by-name/${part%@*}"
done

# mount overlay
mount -t jffs2 /dev/by-name/app /mnt/app
mount -t jffs2 /dev/by-name/overlay /overlay
mount -t jffs2 /dev/by-name/UDISK /mnt/UDISK
mkdir -p /overlay/upper
mkdir -p /overlay/work

# move root
mount -t overlay overlay -o rw,noatime,lowerdir=/,upperdir=/overlay/upper,workdir=/overlay/work /mnt
pivot_root /mnt /mnt/rom

mount -n /rom/dev -o noatime,move /dev
mount -n /rom/overlay -o noatime,move /overlay
mount -n /rom/mnt/app -o noatime,move /mnt/app
mount -n /rom/mnt/UDISK -o noatime,move /mnt/UDISK

exec /linuxrc